package Lexer;

public  enum LexerTYPE {
    VARIABLE,VOID,FUNCTION,FUNCT_NAME,SUM_SUB,MUL_DIV,OPEN_PAREN,CLOSE_PAREN,DIGITAL,TEXT,
    SEMICOLON,EQUAL,VAR_NAME,CHAR,OPEN_BRACKET,CLOSE_BRACKET,RETURN,VISIB_MODIF,COMMA,
    CONDTION,LOOP,TRUE_FALSE,MORE_LESS_EQUAL,ADN_OR,ARR_VAR,ARR_NAME,INCR_DECR
}
